source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target 'Vespucci' do
  pod 'Vespucci', :path => '../'

  target 'Tests' do
    pod 'Specta'
    pod 'Expecta'
  end
end

